jobs:
  test:
    name: Python ${{ matrix.python-version }}, Java ${{ matrix.java-version }}, ${{
      matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
    - continue-on-error: true
      name: Setup Java 8 JDK for build
      uses: actions/setup-java@8db439b6b47e5e12312bf036760bbaa6893481ac
      with:
        cache: gradle
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6
      with:
        python-version: ${{ matrix.python-version }}
    - continue-on-error: true
      name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - continue-on-error: true
      name: Install dependencies
      run: 'pip install pytest

        cd py4j-java

        # Useful in case the build stops working because of version issues.

        ./gradlew --version

        echo `java -version` && echo `javac -version` && echo `python --version`

        echo $PATH

        echo $JAVA_HOME

        ./gradlew clean

        '
      shell: bash
    - continue-on-error: true
      name: Run Gradle tests
      run: 'cd py4j-java

        ./gradlew check

        ./gradlew assemble

        '
    - continue-on-error: true
      if: ${{ matrix.java-version != '8' }}
      name: Setup Java ${{ matrix.java-version }} JDK for PyTest
      uses: actions/setup-java@8db439b6b47e5e12312bf036760bbaa6893481ac
      with:
        cache: gradle
        distribution: adopt
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Run PyTest
      run: 'cd py4j-python

        echo `java -version`

        echo $JAVA_HOME

        # Java TLS tests are disabled until they can be fixed (refs #441)

        pytest -k "not java_tls_test." -vvv

        '
    strategy:
      fail-fast: false
      matrix:
        include:
        - java-version: 8
          os: macos-14
          python-version: '3.12'
        - java-version: 11
          os: windows-2019
          python-version: '3.10'
        - java-version: 17
          os: ubuntu-22.04
          python-version: '3.11'
        - java-version: 21
          os: ubuntu-22.04
          python-version: '3.9'
        java-version:
        - 8
        os:
        - ubuntu-22.04
        python-version:
        - '3.8'
    timeout-minutes: 20
  test-doc:
    name: Documentation build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout master branch
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Install Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - continue-on-error: true
      name: Install Python packages
      run: 'python3 -m pip install -r py4j-web/requirements-doc.txt

        python3 -m pip list

        '
    - continue-on-error: true
      name: Setup Java 8 JDK
      uses: actions/setup-java@v2
      with:
        cache: gradle
        distribution: adopt
        java-version: 8
    - continue-on-error: true
      name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      name: Javadoc build
      run: 'cd py4j-java && ./gradlew javadoc && cd ..

        mv py4j-java/build/docs/javadoc py4j-web/_static/

        '
    - continue-on-error: true
      name: Sphinx build
      run: 'cd py4j-web && make clean html && cd ..

        mv py4j-web/_build/html ../ # Move out of the current repo for GitHub Pages.

        '
    - continue-on-error: true
      if: github.event_name != 'pull_request'
      name: Checkout GitHub Pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
    - continue-on-error: true
      if: github.event_name != 'pull_request'
      name: Copy the generated site
      run: "# Include Javadoc if the commit is tagged (for releases only).\nif [ -z\
        \ \"`git describe --tags --exact-match 2>/dev/null`\" ]; then\n  rm -fr ../html/_static/javadoc\n\
        \  [ -d _static/javadoc ]  && mv _static/javadoc ../html/_static\nfi\n\nrm\
        \ -fr * # Remove existing site\ntouch .nojekyll # See https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages\n\
        echo \"www.py4j.org\" > CNAME # Custom domain for GitHub Actions\ncp -r ../html/*\
        \ . # Move generated site to the current repo.\n"
    - continue-on-error: true
      if: github.event_name != 'pull_request'
      name: Push new site
      uses: EndBug/add-and-commit@v8
      with:
        add: '*'
        default_author: github_actions
        message: Push new site by ${{ github.sha }}
        push: --force
name: test
on:
  repository_dispatch:
    types: trigger-ga___test.yml
